### ISSUE TITLE
Add features to Sim

### ISSUE THREAD

**Issue by serin-delaunay** [serin-delaunay/tracery_game#31]
- [x] Cache state map and AI moves in files in order to generate grammars more quickly (#32)
- [ ] Alt-text
- [ ] Highlight triangles that cause loss
- [ ] Record vertex permutations and report them in replies
- [ ] Allow input formats more general than `1 2`, eg. `12`, `1, 2`, `2 1`
- [ ] Empty lines should be drawn under coloured lines
- [x] Reduce output SVG size so it fits in CBTS preview box (#34)
- [x] State strings should be compressed (#33, #6)
- [ ] Needs messages for game over states
- [ ] AI's `optimal_play` key should be expanded to classify all options as `optimal`, `suboptimal`, or `losing`, for random selection
- [ ] Messages/"taunts" during game to indicate whether the AI expects to win or lose with perfect play. Could even be dependent on previous state and determined by reply selection
